### ISSUE TITLE
Requirements and dependencies are not being installed 

### ISSUE THREAD

**Issue by sageeki** [qadium-memex/CommonCrawlJob#2]
Hi,
I followed your example and edited mrjob to my needs, the cluster shows up as running for 30-60 seconds and than fail with the error of **ccjob python module missing.** 

I'm running the script like that:

python GoogleAnalytics.py -r emr --conf-path="mrjob.conf" --output-dir='s3://findthatdata/out515' index.last 

index.last is the latest link files for the warc files.

My mrjob.conf is like the example with the only difference of instance types and aws key and secret key are there. 

I sshd to the cluster machines and saw that none of the requirements were actually installed, or ccjob being moved to site-packages or anywhere else that python can use it.

Any ideas?

`Probable cause of failure:

R/W/S=943/0/0 in:NA [rec/s] out:NA [rec/s]
minRecWrittenToEnableSkip_=9223372036854775807 HOST=null
USER=hadoop
HADOOP_USER=null
last tool output: |null|

java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:434)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at org.apache.hadoop.streaming.io.TextInputWriter.writeUTF8(TextInputWriter.java:72)
	at org.apache.hadoop.streaming.io.TextInputWriter.writeValue(TextInputWriter.java:51)
	at org.apache.hadoop.streaming.PipeMapper.map(PipeMapper.java:106)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:65)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:432)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:170)

(from lines 48-72 of ssh://ec2-54-164-120-22.compute-1.amazonaws.com!172.31.6.197/mnt/var/log/hadoop/userlogs/application_1472031629066_0001/container_1472031629066_0001_01_000036/syslog)

caused by:

Traceback (most recent call last):
  File "GoogleAnalytics-1.py", line 4, in <module>
    from ccjob import CommonCrawl
ImportError: No module named ccjob

(from lines 1-4 of ssh://ec2-54-164-120-22.compute-1.amazonaws.com!172.31.6.197/mnt/var/log/hadoop/userlogs/application_1472031629066_0001/container_1472031629066_0001_01_000036/stderr)

while reading input from s3://mrjob-c966b2d474a7f5e1/tmp/GoogleAnalytics.root.20160824.093705.862786/files/index.last

Step 1 of 1 failed
Killing our SSH tunnel (pid 1188)
Terminating cluster: j-342PWRARWH0G3`

**Comment by jjangsangy** [comment]
Looks like `ccjob` isn't installed.

I've updated the `pypi` registry so you should add `CommonCrawlJob` to your `requirements.txt`

**Comment by sageeki** [comment]
Seems like that solved the problem. Earlier to that I added to the bootstrap actions to download and install CommonCrawlJob and that also went well.
