### ISSUE TITLE
OverflowError: Unterminated UTF-8 sequence when encoding string

### ISSUE THREAD

**Issue by jroakes** [qadium-memex/CommonCrawlJob#4]
Another error that I have run across is : OverflowError: Unterminated UTF-8 sequence when encoding string error.  

Here is the error log:

```
Probable cause of failure:

PipeMapRed failed!
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
        at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:330)
        at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:543)
        at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:81)
        at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:432)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:170)

(from lines 49-62 of ssh://ec2-54-242-14-147.compute-1.amazonaws.com!10.155.162.51/mnt/var/log/hadoop/userlogs/application_1477157448298
_0001/container_1477157448298_0001_01_000061/syslog)

caused by:

Traceback (most recent call last):
  File "GoogleAnalytics-1.py", line 12, in <module>
    GoogleAnalytics.run()
  File "/usr/local/lib/python2.7/site-packages/mrjob/job.py", line 429, in run
    mr_job.execute()
  File "/usr/local/lib/python2.7/site-packages/mrjob/job.py", line 438, in execute
    self.run_mapper(self.options.step_num)
  File "/usr/local/lib/python2.7/site-packages/mrjob/job.py", line 505, in run_mapper
    write_line(out_key, out_value)
  File "/usr/local/lib/python2.7/site-packages/mrjob/job.py", line 685, in write_line
    self.stdout.write(write(key, value))
  File "/usr/local/lib/python2.7/site-packages/mrjob/protocol.py", line 99, in write
    return self._dumps(key) + b'\t' + self._dumps(value)
  File "/usr/local/lib/python2.7/site-packages/mrjob/protocol.py", line 210, in _dumps
    return ujson.dumps(value)
OverflowError: Unterminated UTF-8 sequence when encoding string
````

In addition, I am getting the following error in the console: Unable to connect to resource manager
This is probably not related and may be the IO behavior you had indicated in the notes.

```
  Opening ssh tunnel to resource manager...
  Connect to resource manager at: http://ip-172-16-0-223:40786/cluster
  RUNNING for 24.0s
Unable to connect to resource manager
  RUNNING for 55.8s
  RUNNING for 86.4s
  RUNNING for 117.4s
  RUNNING for 148.1s
  RUNNING for 178.9s
  RUNNING for 209.0s
  RUNNING for 239.6s
  RUNNING for 270.4s
  RUNNING for 301.4s
```

Any guidance is appreciated.

**Comment by jroakes** [comment]
This was fixed by adding --no-strict-protocols argument to emr:

eg.
```
python GoogleAnalytics.py -r emr --conf-path="mrjob.conf" --no-strict-protocols --output-dir=
's3://s3-bucket/run' data.txt
```

The 
Unable to connect to resource manager

was fixed by commenting out `ssh_tunnel_is_open: true` in mrjob.conf

eg.

`# ssh_tunnel_is_open: true`
