### ISSUE TITLE
Cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by jroakes** [qadium-memex/CommonCrawlJob#5]
I have run the GoogleAnalytics.py script through the entire corpus (after some fiddling) and it finished correctly.  I modified the AdFly.js script a bit to do exception handling, see below:

```
from __future__ import print_function

import sys
from bs4 import BeautifulSoup
from ccjob import CommonCrawl


class DomainExtract(CommonCrawl):

    def process_record(self, body):
        
        
        if (body):
            
            try:
                
                soup = BeautifulSoup(body, 'lxml')
                links = soup.find_all('a')
                
                if len(links) > 0:
                
                    for record in soup.find_all('a'):
                        link = record.attrs.get('href', '')
                        if 'domains.com' in link:
                            yield str(link)                 
            
            except Exception as e:
                sys.stderr.write(str(e.message) + '\n')
            

                                   

if __name__ == '__main__':
    DomainExtract.run()
```

I used a subset of the Warc indexes to test (~80) in run-min.txt (all urls correct, no empty lines).

This is the command I am running:
`python DomainExtract.py -r emr --conf-path="mrjob.conf" --no-strict-protocols --output-dir=
's3://cw-domainextractl/output' run-min.txt`

Using the same mrjob.conf file that worked for the GA run.

This is the error:

```
Probable cause of failure:

PipeMapRed failed!
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 139
        at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:330)
        at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:543)
        at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:81)
        at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:432)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:170)

(from lines 47-60 of ssh://ec2-54-160-195-33.compute-1.amazonaws.com!10.159.136.248/mnt/var/log/hadoop/userlogs/application_14776712
67570_0001/container_1477671267570_0001_01_000053/syslog)

caused by:

cannot concatenate 'str' and 'NoneType' objects
coercing to Unicode: need string or buffer, NoneType found

(from lines 1-2 of ssh://ec2-54-160-195-33.compute-1.amazonaws.com!10.159.136.248/mnt/var/log/hadoop/userlogs/application_1477671267
570_0001/container_1477671267570_0001_01_000053/stderr)

while reading input from s3://mrjob-412b6ccd40683227/tmp/Name.ubuntu.20161028.160827.072829/files/run-min.txt


Step 1 of 1 failed
Killing our SSH tunnel (pid 24301)
Terminating cluster: j-29MBV3ANRYRNC
```

It looks like there is an indication that the error is coming from reading the S3 bucket.  The error seems to happen when using process_record to parse rather than mapper_init.  Wondering if there is anything obvious or a potential bug somewhere that is holding this up.

Thanks for putting this together.

**Comment by jjangsangy** [comment]
This maybe an issue with catching exceptions.
If a generator function calls return or reaches the end its definition, a `StopIteration` exception is raised which maybe emitting a `None`
