### ISSUE TITLE
s3fs error

### ISSUE THREAD

**Issue by 2803media** [qadium-memex/CommonCrawlJob#7]
I try the example and get the following error:

```
[ec2-user@ip-172-31-15-95 CommonCrawlJob-master]$ python examples/GoogleAnalytics.py -r local <(tail -n 1 data/some_file.txt)
No configs found; falling back on auto-configuration
Creating temp directory /tmp/GoogleAnalytics.ec2-user.20170726.211320.330067
Running step 1 of 1...
Traceback (most recent call last):
  File "GoogleAnalytics.py", line 12, in <module>
    GoogleAnalytics.run()
  File "/tmp/GoogleAnalytics.ec2-user.20170726.211320.330067/job_local_dir/0/mapper/1/mrjob.zip/mrjob/job.py", line 439, in run
  File "/tmp/GoogleAnalytics.ec2-user.20170726.211320.330067/job_local_dir/0/mapper/1/mrjob.zip/mrjob/job.py", line 448, in execute
  File "/tmp/GoogleAnalytics.ec2-user.20170726.211320.330067/job_local_dir/0/mapper/1/mrjob.zip/mrjob/job.py", line 526, in run_mapper
  File "/usr/local/lib/python2.7/site-packages/ccjob/commoncrawl.py", line 83, in mapper
    for record in self.read_warc(line.strip()):
  File "/usr/local/lib/python2.7/site-packages/ccjob/commoncrawl.py", line 75, in read_warc
    with self.s3.open(keypath, 'rb') as fp:
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 293, in open
    fill_cache=fill_cache, s3_additional_kwargs=kwargs)
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 931, in __init__
    self.size = self.info()['Size']
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 940, in info
    return self.s3.info(self.path, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 402, in info
    raise FileNotFoundError(path)
s3fs.core.FileNotFoundError: aws-publicdatasets/common-crawl/crawl-data/CC-MAIN-2017-26/segments/1498128319265.41/warc/CC-MAIN-20170622114718-20170622134718-00000.warc.gz
Step 1 of 1 failed: Command '['sh', '-ex', 'setup-wrapper.sh', '/usr/bin/python', 'GoogleAnalytics.py', '--step-num=0', '--mapper']' returned non-zero exit status 1

```

Do you have any info on this please?

**Comment by jjangsangy** [comment]
Hey @2803 

So it looks like Common Crawl has updated their S3 bucket from

[`s3://aws-publicdatasets/common-crawl/` -> `s3://common-crawl/` in US East Region](https://commoncrawl.org/the-data/get-started/)

Update your `data/some_file.txt` so that it points to the actual WARC file and let me know if that fixed the problem.

**Comment by 2803media** [comment]
thanks i will change that!
